#!/bin/bash

JAVACMD=$(which java 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "JAVA is required to run foreman-host-configurator"
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JAR_FILE=${SCRIPT_DIR}/foreman-host-configurator.jar

if [ ! -e "${JAR_FILE}" ] ; then
    if [ ! -e "${SCRIPT_DIR}/target/foreman-host-configurator.jar" ] ; then
        MVNCMD=$(which mvn 2> /dev/null)
        if [ $? -ne 0 ] ; then
          echo "Maven is required to build foreman-host-configurator"
          exit 1
        fi
        echo "Building foreman-host-configurator..."
        mvn package -DskipTests -q
        if [ $? -ne 0 ] ; then
            echo "Failed to build foreman-host-configurator!"
            exit 1
        fi
        echo "Done"
    fi
    JAR_FILE=${SCRIPT_DIR}/target/foreman-host-configurator.jar
fi

$JAVACMD -jar "${JAR_FILE}" "$*"
exit $?
